### ISSUE TITLE
Tutorials of MCTS or Retro* for single retro synthesis model 【Help wanted】

### ISSUE THREAD

**Issue by zw-SIMM** [microsoft/syntheseus#64]
I have noted that you provided the use of AndOr_BreadthFirstSearch in ```1- end to end retrosynthesis with a toy model.ipynb``` and reproduced PaRoutes in ```2a- advanced algorithms on PaRoutes.ipynb```.

Could you provide an example of using Retro* or MCTS for template-free models like Root-Aligned? Many Thanks.

**Comment by AustinT** [comment]
> I have noted that you provided the use of AndOr_BreadthFirstSearch in `1- end to end retrosynthesis with a toy model.ipynb` and reproduced PaRoutes in `2a- advanced algorithms on PaRoutes.ipynb`.
> 
> Could you provide an example of using Retro* or MCTS for template-free models like Root-Aligned? Many Thanks.

Hello @zw-SIMM. You can put one of the template free models into the syntheseus wrapper class here: https://github.com/microsoft/syntheseus/blob/main/syntheseus/reaction_prediction/utils/syntheseus_wrapper.py

However, as mentioned in #58 we are in the process of making this simpler, and in the upcoming v0.4.0 release you will be able to directly put the template-free models into the algorithms without a wrapper class. I hope this release will be available in 1 week or so.

**Comment by zw-SIMM** [comment]
Thanks again for your nice reply! Great work!! Really Learn a lot!!!

**Comment by kmaziarz** [comment]
We're still working towards the simplification mention by Austin, but in the meantime, [this tutorial](https://microsoft.github.io/syntheseus/tutorials/quick_start/) shows explicitly how to use the wrapper class. Hope this helps and let us know if you run into any issues.

**Comment by zw-SIMM** [comment]
> We're still working towards the simplification mention by Austin, but in the meantime, [this tutorial](https://microsoft.github.io/syntheseus/tutorials/quick_start/) shows explicitly how to use the wrapper class. Hope this helps and let us know if you run into any issues.

Clear! Run successfully!
