### ISSUE TITLE
About local_retro package 

### ISSUE THREAD

**Issue by liugangcode** [microsoft/syntheseus#95]
Hi team, thanks for the great work! I wonder what's the local_retro package, which is used in the LocalRetroModel class?

**Comment by AustinT** [comment]
Hello @liugangcode, it is the syntheseus local retro library [here](https://pypi.org/project/syntheseus-local-retro/). You can see the requirement for it [here](https://github.com/microsoft/syntheseus/blob/feb813de62b259932e2a864f0475e10fa6f4b14d/pyproject.toml#L40) in the `pyproject.toml` file. It is a minimally-modified version of the original code.

I will close this issue for now, but please do respond if you have further questions.
